module.exports = [
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
  {
    dateModified: null,
    idMeal: "53038",
    strArea: "Irish",
    strCategory: "Side",
    strDrinkAlternate: null,
    strIngredient1: "Potatoes",
    strIngredient2: "Milk",
    strIngredient3: "Butter",
    strIngredient4: "Mustard",
    strIngredient5: "Spring Onions",
    strIngredient6: "Spring Onions",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strInstructions:
      "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash.STEP 2Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
    strMeal: "Mustard champ",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
    strMeasure1: "1kg",
    strMeasure2: "200ml",
    strMeasure3: "50g",
    strMeasure4: "2 tbs",
    strMeasure5: "Bunch",
    strMeasure6: "Bunch",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
  },
];
